"""Generates cpp/powergrid_data.inc from the tables in powergrid_core.py, so the
C++ engine never carries a hand-copied table.

    python3 tools/gen_cpp_data.py          # rewrite the file
    python3 tools/gen_cpp_data.py --check  # exit 1 if it is out of date
"""
import os
import sys

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
sys.path.insert(0, ROOT)
import powergrid_core as pg  # noqa: E402

OUT = os.path.join(ROOT, "cpp", "powergrid_data.inc")
KIND = {"coal": "kKindCoal", "oil": "kKindOil", "garbage": "kKindGarbage",
        "uranium": "kKindUranium", "hybrid": "kKindHybrid", "eco": "kKindEco"}


def cstr(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render_map(fn, m):
    out = [f"MapSpec {fn}() {{", "  return MapSpec("]
    out.append(f"      {cstr(m.name)},")
    out.append("      {" + ", ".join(cstr(n) for n in m.city_names) + "},")
    out.append("      {" + ", ".join(map(str, m.city_region)) + "},")
    out.append("      {" + ", ".join(cstr(n) for n in m.region_names) + "},")
    out.append("      {")
    for a, b, w in m.edges:
        out.append(f"          {{{a}, {b}, {w}}},  // {m.city_names[a]} - {m.city_names[b]}")
    out.append("      },")
    out.append(f"      /*nuclear_phase_out=*/{'true' if m.nuclear_phase_out else 'false'});")
    out.append("}")
    return out


def render():
    out = ["// GENERATED by tools/gen_cpp_data.py from powergrid_core.py -- do not edit.",
           "// Included inside namespace powergrid by powergrid_engine.cc.", ""]
    out.append("const std::vector<Plant>& Plants() {")
    out.append("  static const std::vector<Plant> plants = {")
    for p in pg.PLANTS:
        out.append(f"      {{{p.number}, {KIND[p.kind]}, {p.need}, {p.power}}},")
    out += ["  };", "  return plants;", "}", ""]

    out.append("namespace {")
    out.append("// RESUPPLY[players][step-1] = (coal, oil, garbage, uranium)")
    out.append("constexpr std::array<std::array<std::array<int, 4>, 3>, kMaxPlayers + 1> kResupply = {{")
    for n in range(7):
        if n in pg.RESUPPLY:
            rows = ", ".join("{" + ", ".join(map(str, r)) + "}" for r in pg.RESUPPLY[n])
            out.append(f"    {{{{{rows}}}}},  // {n} players")
        else:
            out.append("    {},")
    out.append("}};")
    out.append("// (areas, plug plants removed, socket plants removed, plant limit, step-2 trigger,")
    out.append("//  game end)")
    out.append("constexpr std::array<std::array<int, 6>, kMaxPlayers + 1> kPlayerCountRules = {{")
    for n in range(7):
        row = pg.PLAYER_COUNT_RULES.get(n)
        out.append("    {" + (", ".join(map(str, row)) if row else "") + "},")
    out.append("}};")
    out.append("const std::vector<int> kIncome = {" + ", ".join(map(str, pg.INCOME)) + "};")
    out.append(f"constexpr int kHousesPerPlayer = {pg.HOUSES_PER_PLAYER};")
    assert (pg.MAX_PLUG, pg.NUCLEAR_PHASE_OUT_PLANT, pg.TRUST_HOUSES, pg.TRUST_START_HOUSES) == \
        (15, 39, 16, 6), "update the constants in powergrid_engine.h"
    out.append("}  // namespace")
    out.append("")
    out += render_map("GermanyMap", pg.germany_map())
    out.append("")
    out += render_map("Germany2004Map", pg.germany_2004_map())
    return "\n".join(out) + "\n"


if __name__ == "__main__":
    text = render()
    if "--check" in sys.argv:
        current = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""
        if current != text:
            print(f"{OUT} is out of date: run python3 tools/gen_cpp_data.py")
            sys.exit(1)
        print("cpp/powergrid_data.inc is up to date")
    else:
        open(OUT, "w", encoding="utf-8").write(text)
        print("wrote", OUT)
